// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: com/android/aapt/ResourcesInternal.proto
// Protobuf Java Version: 4.27.0

package android.aapt.pb.internal;

public final class ResourcesInternal {
  private ResourcesInternal() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }
  public interface CompiledFileOrBuilder extends
      // @@protoc_insertion_point(interface_extends:CompiledFile)
      com.google.protobuf.MessageLiteOrBuilder {

    /**
     * <pre>
     * The name of the resource (in the form package:type/name).
     * </pre>
     *
     * <code>string resource_name = 1;</code>
     * @return The resourceName.
     */
    java.lang.String getResourceName();
    /**
     * <pre>
     * The name of the resource (in the form package:type/name).
     * </pre>
     *
     * <code>string resource_name = 1;</code>
     * @return The bytes for resourceName.
     */
    com.google.protobuf.ByteString
        getResourceNameBytes();

    /**
     * <pre>
     * The configuration for which the resource is defined.
     * </pre>
     *
     * <code>.Configuration config = 2;</code>
     * @return Whether the config field is set.
     */
    boolean hasConfig();
    /**
     * <pre>
     * The configuration for which the resource is defined.
     * </pre>
     *
     * <code>.Configuration config = 2;</code>
     * @return The config.
     */
    com.android.aapt.ConfigurationOuterClass.Configuration getConfig();

    /**
     * <pre>
     * The type of the file.
     * </pre>
     *
     * <code>.FileReference.Type type = 3;</code>
     * @return The enum numeric value on the wire for type.
     */
    int getTypeValue();
    /**
     * <pre>
     * The type of the file.
     * </pre>
     *
     * <code>.FileReference.Type type = 3;</code>
     * @return The type.
     */
    com.android.aapt.Resources.FileReference.Type getType();

    /**
     * <pre>
     * The filesystem path to where the source file originated.
     * Mainly used to display helpful error messages.
     * </pre>
     *
     * <code>string source_path = 4;</code>
     * @return The sourcePath.
     */
    java.lang.String getSourcePath();
    /**
     * <pre>
     * The filesystem path to where the source file originated.
     * Mainly used to display helpful error messages.
     * </pre>
     *
     * <code>string source_path = 4;</code>
     * @return The bytes for sourcePath.
     */
    com.google.protobuf.ByteString
        getSourcePathBytes();

    /**
     * <pre>
     * Any symbols this file auto-generates/exports (eg. &#64;+id/foo in an XML file).
     * </pre>
     *
     * <code>repeated .CompiledFile.Symbol exported_symbol = 5;</code>
     */
    java.util.List<android.aapt.pb.internal.ResourcesInternal.CompiledFile.Symbol> 
        getExportedSymbolList();
    /**
     * <pre>
     * Any symbols this file auto-generates/exports (eg. &#64;+id/foo in an XML file).
     * </pre>
     *
     * <code>repeated .CompiledFile.Symbol exported_symbol = 5;</code>
     */
    android.aapt.pb.internal.ResourcesInternal.CompiledFile.Symbol getExportedSymbol(int index);
    /**
     * <pre>
     * Any symbols this file auto-generates/exports (eg. &#64;+id/foo in an XML file).
     * </pre>
     *
     * <code>repeated .CompiledFile.Symbol exported_symbol = 5;</code>
     */
    int getExportedSymbolCount();
  }
  /**
   * <pre>
   * The top level message representing an external resource file (layout XML, PNG, etc).
   * This is used to represent a compiled file before it is linked. Only useful to aapt2.
   * </pre>
   *
   * Protobuf type {@code CompiledFile}
   */
  public  static final class CompiledFile extends
      com.google.protobuf.GeneratedMessageLite<
          CompiledFile, CompiledFile.Builder> implements
      // @@protoc_insertion_point(message_implements:CompiledFile)
      CompiledFileOrBuilder {
    private CompiledFile() {
      resourceName_ = "";
      sourcePath_ = "";
      exportedSymbol_ = emptyProtobufList();
    }
    public interface SymbolOrBuilder extends
        // @@protoc_insertion_point(interface_extends:CompiledFile.Symbol)
        com.google.protobuf.MessageLiteOrBuilder {

      /**
       * <pre>
       * The name of the symbol (in the form package:type/name).
       * </pre>
       *
       * <code>string resource_name = 1;</code>
       * @return The resourceName.
       */
      java.lang.String getResourceName();
      /**
       * <pre>
       * The name of the symbol (in the form package:type/name).
       * </pre>
       *
       * <code>string resource_name = 1;</code>
       * @return The bytes for resourceName.
       */
      com.google.protobuf.ByteString
          getResourceNameBytes();

      /**
       * <pre>
       * The position in the file at which this symbol is defined. For debug use.
       * </pre>
       *
       * <code>.SourcePosition source = 2;</code>
       * @return Whether the source field is set.
       */
      boolean hasSource();
      /**
       * <pre>
       * The position in the file at which this symbol is defined. For debug use.
       * </pre>
       *
       * <code>.SourcePosition source = 2;</code>
       * @return The source.
       */
      com.android.aapt.Resources.SourcePosition getSource();
    }
    /**
     * Protobuf type {@code CompiledFile.Symbol}
     */
    public  static final class Symbol extends
        com.google.protobuf.GeneratedMessageLite<
            Symbol, Symbol.Builder> implements
        // @@protoc_insertion_point(message_implements:CompiledFile.Symbol)
        SymbolOrBuilder {
      private Symbol() {
        resourceName_ = "";
      }
      private int bitField0_;
      public static final int RESOURCE_NAME_FIELD_NUMBER = 1;
      private java.lang.String resourceName_;
      /**
       * <pre>
       * The name of the symbol (in the form package:type/name).
       * </pre>
       *
       * <code>string resource_name = 1;</code>
       * @return The resourceName.
       */
      @java.lang.Override
      public java.lang.String getResourceName() {
        return resourceName_;
      }
      /**
       * <pre>
       * The name of the symbol (in the form package:type/name).
       * </pre>
       *
       * <code>string resource_name = 1;</code>
       * @return The bytes for resourceName.
       */
      @java.lang.Override
      public com.google.protobuf.ByteString
          getResourceNameBytes() {
        return com.google.protobuf.ByteString.copyFromUtf8(resourceName_);
      }
      /**
       * <pre>
       * The name of the symbol (in the form package:type/name).
       * </pre>
       *
       * <code>string resource_name = 1;</code>
       * @param value The resourceName to set.
       */
      private void setResourceName(
          java.lang.String value) {
        java.lang.Class<?> valueClass = value.getClass();
  
        resourceName_ = value;
      }
      /**
       * <pre>
       * The name of the symbol (in the form package:type/name).
       * </pre>
       *
       * <code>string resource_name = 1;</code>
       */
      private void clearResourceName() {

        resourceName_ = getDefaultInstance().getResourceName();
      }
      /**
       * <pre>
       * The name of the symbol (in the form package:type/name).
       * </pre>
       *
       * <code>string resource_name = 1;</code>
       * @param value The bytes for resourceName to set.
       */
      private void setResourceNameBytes(
          com.google.protobuf.ByteString value) {
        checkByteStringIsUtf8(value);
        resourceName_ = value.toStringUtf8();

      }

      public static final int SOURCE_FIELD_NUMBER = 2;
      private com.android.aapt.Resources.SourcePosition source_;
      /**
       * <pre>
       * The position in the file at which this symbol is defined. For debug use.
       * </pre>
       *
       * <code>.SourcePosition source = 2;</code>
       */
      @java.lang.Override
      public boolean hasSource() {
        return ((bitField0_ & 0x00000001) != 0);
      }
      /**
       * <pre>
       * The position in the file at which this symbol is defined. For debug use.
       * </pre>
       *
       * <code>.SourcePosition source = 2;</code>
       */
      @java.lang.Override
      public com.android.aapt.Resources.SourcePosition getSource() {
        return source_ == null ? com.android.aapt.Resources.SourcePosition.getDefaultInstance() : source_;
      }
      /**
       * <pre>
       * The position in the file at which this symbol is defined. For debug use.
       * </pre>
       *
       * <code>.SourcePosition source = 2;</code>
       */
      private void setSource(com.android.aapt.Resources.SourcePosition value) {
        value.getClass();
  source_ = value;
        bitField0_ |= 0x00000001;
        }
      /**
       * <pre>
       * The position in the file at which this symbol is defined. For debug use.
       * </pre>
       *
       * <code>.SourcePosition source = 2;</code>
       */
      @java.lang.SuppressWarnings({"ReferenceEquality"})
      private void mergeSource(com.android.aapt.Resources.SourcePosition value) {
        value.getClass();
  if (source_ != null &&
            source_ != com.android.aapt.Resources.SourcePosition.getDefaultInstance()) {
          source_ =
            com.android.aapt.Resources.SourcePosition.newBuilder(source_).mergeFrom(value).buildPartial();
        } else {
          source_ = value;
        }
        bitField0_ |= 0x00000001;
      }
      /**
       * <pre>
       * The position in the file at which this symbol is defined. For debug use.
       * </pre>
       *
       * <code>.SourcePosition source = 2;</code>
       */
      private void clearSource() {  source_ = null;
        bitField0_ = (bitField0_ & ~0x00000001);
      }

      public static android.aapt.pb.internal.ResourcesInternal.CompiledFile.Symbol parseFrom(
          java.nio.ByteBuffer data)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return com.google.protobuf.GeneratedMessageLite.parseFrom(
            DEFAULT_INSTANCE, data);
      }
      public static android.aapt.pb.internal.ResourcesInternal.CompiledFile.Symbol parseFrom(
          java.nio.ByteBuffer data,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return com.google.protobuf.GeneratedMessageLite.parseFrom(
            DEFAULT_INSTANCE, data, extensionRegistry);
      }
      public static android.aapt.pb.internal.ResourcesInternal.CompiledFile.Symbol parseFrom(
          com.google.protobuf.ByteString data)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return com.google.protobuf.GeneratedMessageLite.parseFrom(
            DEFAULT_INSTANCE, data);
      }
      public static android.aapt.pb.internal.ResourcesInternal.CompiledFile.Symbol parseFrom(
          com.google.protobuf.ByteString data,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return com.google.protobuf.GeneratedMessageLite.parseFrom(
            DEFAULT_INSTANCE, data, extensionRegistry);
      }
      public static android.aapt.pb.internal.ResourcesInternal.CompiledFile.Symbol parseFrom(byte[] data)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return com.google.protobuf.GeneratedMessageLite.parseFrom(
            DEFAULT_INSTANCE, data);
      }
      public static android.aapt.pb.internal.ResourcesInternal.CompiledFile.Symbol parseFrom(
          byte[] data,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return com.google.protobuf.GeneratedMessageLite.parseFrom(
            DEFAULT_INSTANCE, data, extensionRegistry);
      }
      public static android.aapt.pb.internal.ResourcesInternal.CompiledFile.Symbol parseFrom(java.io.InputStream input)
          throws java.io.IOException {
        return com.google.protobuf.GeneratedMessageLite.parseFrom(
            DEFAULT_INSTANCE, input);
      }
      public static android.aapt.pb.internal.ResourcesInternal.CompiledFile.Symbol parseFrom(
          java.io.InputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        return com.google.protobuf.GeneratedMessageLite.parseFrom(
            DEFAULT_INSTANCE, input, extensionRegistry);
      }

      public static android.aapt.pb.internal.ResourcesInternal.CompiledFile.Symbol parseDelimitedFrom(java.io.InputStream input)
          throws java.io.IOException {
        return parseDelimitedFrom(DEFAULT_INSTANCE, input);
      }

      public static android.aapt.pb.internal.ResourcesInternal.CompiledFile.Symbol parseDelimitedFrom(
          java.io.InputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        return parseDelimitedFrom(DEFAULT_INSTANCE, input, extensionRegistry);
      }
      public static android.aapt.pb.internal.ResourcesInternal.CompiledFile.Symbol parseFrom(
          com.google.protobuf.CodedInputStream input)
          throws java.io.IOException {
        return com.google.protobuf.GeneratedMessageLite.parseFrom(
            DEFAULT_INSTANCE, input);
      }
      public static android.aapt.pb.internal.ResourcesInternal.CompiledFile.Symbol parseFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        return com.google.protobuf.GeneratedMessageLite.parseFrom(
            DEFAULT_INSTANCE, input, extensionRegistry);
      }

      public static Builder newBuilder() {
        return (Builder) DEFAULT_INSTANCE.createBuilder();
      }
      public static Builder newBuilder(android.aapt.pb.internal.ResourcesInternal.CompiledFile.Symbol prototype) {
        return DEFAULT_INSTANCE.createBuilder(prototype);
      }

      /**
       * Protobuf type {@code CompiledFile.Symbol}
       */
      public static final class Builder extends
          com.google.protobuf.GeneratedMessageLite.Builder<
            android.aapt.pb.internal.ResourcesInternal.CompiledFile.Symbol, Builder> implements
          // @@protoc_insertion_point(builder_implements:CompiledFile.Symbol)
          android.aapt.pb.internal.ResourcesInternal.CompiledFile.SymbolOrBuilder {
        // Construct using android.aapt.pb.internal.ResourcesInternal.CompiledFile.Symbol.newBuilder()
        private Builder() {
          super(DEFAULT_INSTANCE);
        }


        /**
         * <pre>
         * The name of the symbol (in the form package:type/name).
         * </pre>
         *
         * <code>string resource_name = 1;</code>
         * @return The resourceName.
         */
        @java.lang.Override
        public java.lang.String getResourceName() {
          return instance.getResourceName();
        }
        /**
         * <pre>
         * The name of the symbol (in the form package:type/name).
         * </pre>
         *
         * <code>string resource_name = 1;</code>
         * @return The bytes for resourceName.
         */
        @java.lang.Override
        public com.google.protobuf.ByteString
            getResourceNameBytes() {
          return instance.getResourceNameBytes();
        }
        /**
         * <pre>
         * The name of the symbol (in the form package:type/name).
         * </pre>
         *
         * <code>string resource_name = 1;</code>
         * @param value The resourceName to set.
         * @return This builder for chaining.
         */
        public Builder setResourceName(
            java.lang.String value) {
          copyOnWrite();
          instance.setResourceName(value);
          return this;
        }
        /**
         * <pre>
         * The name of the symbol (in the form package:type/name).
         * </pre>
         *
         * <code>string resource_name = 1;</code>
         * @return This builder for chaining.
         */
        public Builder clearResourceName() {
          copyOnWrite();
          instance.clearResourceName();
          return this;
        }
        /**
         * <pre>
         * The name of the symbol (in the form package:type/name).
         * </pre>
         *
         * <code>string resource_name = 1;</code>
         * @param value The bytes for resourceName to set.
         * @return This builder for chaining.
         */
        public Builder setResourceNameBytes(
            com.google.protobuf.ByteString value) {
          copyOnWrite();
          instance.setResourceNameBytes(value);
          return this;
        }

        /**
         * <pre>
         * The position in the file at which this symbol is defined. For debug use.
         * </pre>
         *
         * <code>.SourcePosition source = 2;</code>
         */
        @java.lang.Override
        public boolean hasSource() {
          return instance.hasSource();
        }
        /**
         * <pre>
         * The position in the file at which this symbol is defined. For debug use.
         * </pre>
         *
         * <code>.SourcePosition source = 2;</code>
         */
        @java.lang.Override
        public com.android.aapt.Resources.SourcePosition getSource() {
          return instance.getSource();
        }
        /**
         * <pre>
         * The position in the file at which this symbol is defined. For debug use.
         * </pre>
         *
         * <code>.SourcePosition source = 2;</code>
         */
        public Builder setSource(com.android.aapt.Resources.SourcePosition value) {
          copyOnWrite();
          instance.setSource(value);
          return this;
          }
        /**
         * <pre>
         * The position in the file at which this symbol is defined. For debug use.
         * </pre>
         *
         * <code>.SourcePosition source = 2;</code>
         */
        public Builder setSource(
            com.android.aapt.Resources.SourcePosition.Builder builderForValue) {
          copyOnWrite();
          instance.setSource(builderForValue.build());
          return this;
        }
        /**
         * <pre>
         * The position in the file at which this symbol is defined. For debug use.
         * </pre>
         *
         * <code>.SourcePosition source = 2;</code>
         */
        public Builder mergeSource(com.android.aapt.Resources.SourcePosition value) {
          copyOnWrite();
          instance.mergeSource(value);
          return this;
        }
        /**
         * <pre>
         * The position in the file at which this symbol is defined. For debug use.
         * </pre>
         *
         * <code>.SourcePosition source = 2;</code>
         */
        public Builder clearSource() {  copyOnWrite();
          instance.clearSource();
          return this;
        }

        // @@protoc_insertion_point(builder_scope:CompiledFile.Symbol)
      }
      @java.lang.Override
      @java.lang.SuppressWarnings({"unchecked", "fallthrough"})
      protected final java.lang.Object dynamicMethod(
          com.google.protobuf.GeneratedMessageLite.MethodToInvoke method,
          java.lang.Object arg0, java.lang.Object arg1) {
        switch (method) {
          case NEW_MUTABLE_INSTANCE: {
            return new android.aapt.pb.internal.ResourcesInternal.CompiledFile.Symbol();
          }
          case NEW_BUILDER: {
            return new Builder();
          }
          case BUILD_MESSAGE_INFO: {
              java.lang.Object[] objects = new java.lang.Object[] {
                "bitField0_",
                "resourceName_",
                "source_",
              };
              java.lang.String info =
                  "\u0000\u0002\u0000\u0001\u0001\u0002\u0002\u0000\u0000\u0000\u0001\u0208\u0002\u1009" +
                  "\u0000";
              return newMessageInfo(DEFAULT_INSTANCE, info, objects);
          }
          // fall through
          case GET_DEFAULT_INSTANCE: {
            return DEFAULT_INSTANCE;
          }
          case GET_PARSER: {
            com.google.protobuf.Parser<android.aapt.pb.internal.ResourcesInternal.CompiledFile.Symbol> parser = PARSER;
            if (parser == null) {
              synchronized (android.aapt.pb.internal.ResourcesInternal.CompiledFile.Symbol.class) {
                parser = PARSER;
                if (parser == null) {
                  parser =
                      new DefaultInstanceBasedParser<android.aapt.pb.internal.ResourcesInternal.CompiledFile.Symbol>(
                          DEFAULT_INSTANCE);
                  PARSER = parser;
                }
              }
            }
            return parser;
        }
        case GET_MEMOIZED_IS_INITIALIZED: {
          return (byte) 1;
        }
        case SET_MEMOIZED_IS_INITIALIZED: {
          return null;
        }
        }
        throw new UnsupportedOperationException();
      }


      // @@protoc_insertion_point(class_scope:CompiledFile.Symbol)
      private static final android.aapt.pb.internal.ResourcesInternal.CompiledFile.Symbol DEFAULT_INSTANCE;
      static {
        Symbol defaultInstance = new Symbol();
        // New instances are implicitly immutable so no need to make
        // immutable.
        DEFAULT_INSTANCE = defaultInstance;
        com.google.protobuf.GeneratedMessageLite.registerDefaultInstance(
          Symbol.class, defaultInstance);
      }

      public static android.aapt.pb.internal.ResourcesInternal.CompiledFile.Symbol getDefaultInstance() {
        return DEFAULT_INSTANCE;
      }

      private static volatile com.google.protobuf.Parser<Symbol> PARSER;

      public static com.google.protobuf.Parser<Symbol> parser() {
        return DEFAULT_INSTANCE.getParserForType();
      }
    }

    private int bitField0_;
    public static final int RESOURCE_NAME_FIELD_NUMBER = 1;
    private java.lang.String resourceName_;
    /**
     * <pre>
     * The name of the resource (in the form package:type/name).
     * </pre>
     *
     * <code>string resource_name = 1;</code>
     * @return The resourceName.
     */
    @java.lang.Override
    public java.lang.String getResourceName() {
      return resourceName_;
    }
    /**
     * <pre>
     * The name of the resource (in the form package:type/name).
     * </pre>
     *
     * <code>string resource_name = 1;</code>
     * @return The bytes for resourceName.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getResourceNameBytes() {
      return com.google.protobuf.ByteString.copyFromUtf8(resourceName_);
    }
    /**
     * <pre>
     * The name of the resource (in the form package:type/name).
     * </pre>
     *
     * <code>string resource_name = 1;</code>
     * @param value The resourceName to set.
     */
    private void setResourceName(
        java.lang.String value) {
      java.lang.Class<?> valueClass = value.getClass();
  
      resourceName_ = value;
    }
    /**
     * <pre>
     * The name of the resource (in the form package:type/name).
     * </pre>
     *
     * <code>string resource_name = 1;</code>
     */
    private void clearResourceName() {

      resourceName_ = getDefaultInstance().getResourceName();
    }
    /**
     * <pre>
     * The name of the resource (in the form package:type/name).
     * </pre>
     *
     * <code>string resource_name = 1;</code>
     * @param value The bytes for resourceName to set.
     */
    private void setResourceNameBytes(
        com.google.protobuf.ByteString value) {
      checkByteStringIsUtf8(value);
      resourceName_ = value.toStringUtf8();

    }

    public static final int CONFIG_FIELD_NUMBER = 2;
    private com.android.aapt.ConfigurationOuterClass.Configuration config_;
    /**
     * <pre>
     * The configuration for which the resource is defined.
     * </pre>
     *
     * <code>.Configuration config = 2;</code>
     */
    @java.lang.Override
    public boolean hasConfig() {
      return ((bitField0_ & 0x00000001) != 0);
    }
    /**
     * <pre>
     * The configuration for which the resource is defined.
     * </pre>
     *
     * <code>.Configuration config = 2;</code>
     */
    @java.lang.Override
    public com.android.aapt.ConfigurationOuterClass.Configuration getConfig() {
      return config_ == null ? com.android.aapt.ConfigurationOuterClass.Configuration.getDefaultInstance() : config_;
    }
    /**
     * <pre>
     * The configuration for which the resource is defined.
     * </pre>
     *
     * <code>.Configuration config = 2;</code>
     */
    private void setConfig(com.android.aapt.ConfigurationOuterClass.Configuration value) {
      value.getClass();
  config_ = value;
      bitField0_ |= 0x00000001;
      }
    /**
     * <pre>
     * The configuration for which the resource is defined.
     * </pre>
     *
     * <code>.Configuration config = 2;</code>
     */
    @java.lang.SuppressWarnings({"ReferenceEquality"})
    private void mergeConfig(com.android.aapt.ConfigurationOuterClass.Configuration value) {
      value.getClass();
  if (config_ != null &&
          config_ != com.android.aapt.ConfigurationOuterClass.Configuration.getDefaultInstance()) {
        config_ =
          com.android.aapt.ConfigurationOuterClass.Configuration.newBuilder(config_).mergeFrom(value).buildPartial();
      } else {
        config_ = value;
      }
      bitField0_ |= 0x00000001;
    }
    /**
     * <pre>
     * The configuration for which the resource is defined.
     * </pre>
     *
     * <code>.Configuration config = 2;</code>
     */
    private void clearConfig() {  config_ = null;
      bitField0_ = (bitField0_ & ~0x00000001);
    }

    public static final int TYPE_FIELD_NUMBER = 3;
    private int type_;
    /**
     * <pre>
     * The type of the file.
     * </pre>
     *
     * <code>.FileReference.Type type = 3;</code>
     * @return The enum numeric value on the wire for type.
     */
    @java.lang.Override
    public int getTypeValue() {
      return type_;
    }
    /**
     * <pre>
     * The type of the file.
     * </pre>
     *
     * <code>.FileReference.Type type = 3;</code>
     * @return The type.
     */
    @java.lang.Override
    public com.android.aapt.Resources.FileReference.Type getType() {
      com.android.aapt.Resources.FileReference.Type result = com.android.aapt.Resources.FileReference.Type.forNumber(type_);
      return result == null ? com.android.aapt.Resources.FileReference.Type.UNRECOGNIZED : result;
    }
    /**
     * <pre>
     * The type of the file.
     * </pre>
     *
     * <code>.FileReference.Type type = 3;</code>
     * @param value The enum numeric value on the wire for type to set.
     */
    private void setTypeValue(int value) {
        type_ = value;
    }
    /**
     * <pre>
     * The type of the file.
     * </pre>
     *
     * <code>.FileReference.Type type = 3;</code>
     * @param value The type to set.
     */
    private void setType(com.android.aapt.Resources.FileReference.Type value) {
      type_ = value.getNumber();

    }
    /**
     * <pre>
     * The type of the file.
     * </pre>
     *
     * <code>.FileReference.Type type = 3;</code>
     */
    private void clearType() {

      type_ = 0;
    }

    public static final int SOURCE_PATH_FIELD_NUMBER = 4;
    private java.lang.String sourcePath_;
    /**
     * <pre>
     * The filesystem path to where the source file originated.
     * Mainly used to display helpful error messages.
     * </pre>
     *
     * <code>string source_path = 4;</code>
     * @return The sourcePath.
     */
    @java.lang.Override
    public java.lang.String getSourcePath() {
      return sourcePath_;
    }
    /**
     * <pre>
     * The filesystem path to where the source file originated.
     * Mainly used to display helpful error messages.
     * </pre>
     *
     * <code>string source_path = 4;</code>
     * @return The bytes for sourcePath.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getSourcePathBytes() {
      return com.google.protobuf.ByteString.copyFromUtf8(sourcePath_);
    }
    /**
     * <pre>
     * The filesystem path to where the source file originated.
     * Mainly used to display helpful error messages.
     * </pre>
     *
     * <code>string source_path = 4;</code>
     * @param value The sourcePath to set.
     */
    private void setSourcePath(
        java.lang.String value) {
      java.lang.Class<?> valueClass = value.getClass();
  
      sourcePath_ = value;
    }
    /**
     * <pre>
     * The filesystem path to where the source file originated.
     * Mainly used to display helpful error messages.
     * </pre>
     *
     * <code>string source_path = 4;</code>
     */
    private void clearSourcePath() {

      sourcePath_ = getDefaultInstance().getSourcePath();
    }
    /**
     * <pre>
     * The filesystem path to where the source file originated.
     * Mainly used to display helpful error messages.
     * </pre>
     *
     * <code>string source_path = 4;</code>
     * @param value The bytes for sourcePath to set.
     */
    private void setSourcePathBytes(
        com.google.protobuf.ByteString value) {
      checkByteStringIsUtf8(value);
      sourcePath_ = value.toStringUtf8();

    }

    public static final int EXPORTED_SYMBOL_FIELD_NUMBER = 5;
    private com.google.protobuf.Internal.ProtobufList<android.aapt.pb.internal.ResourcesInternal.CompiledFile.Symbol> exportedSymbol_;
    /**
     * <pre>
     * Any symbols this file auto-generates/exports (eg. &#64;+id/foo in an XML file).
     * </pre>
     *
     * <code>repeated .CompiledFile.Symbol exported_symbol = 5;</code>
     */
    @java.lang.Override
    public java.util.List<android.aapt.pb.internal.ResourcesInternal.CompiledFile.Symbol> getExportedSymbolList() {
      return exportedSymbol_;
    }
    /**
     * <pre>
     * Any symbols this file auto-generates/exports (eg. &#64;+id/foo in an XML file).
     * </pre>
     *
     * <code>repeated .CompiledFile.Symbol exported_symbol = 5;</code>
     */
    public java.util.List<? extends android.aapt.pb.internal.ResourcesInternal.CompiledFile.SymbolOrBuilder> 
        getExportedSymbolOrBuilderList() {
      return exportedSymbol_;
    }
    /**
     * <pre>
     * Any symbols this file auto-generates/exports (eg. &#64;+id/foo in an XML file).
     * </pre>
     *
     * <code>repeated .CompiledFile.Symbol exported_symbol = 5;</code>
     */
    @java.lang.Override
    public int getExportedSymbolCount() {
      return exportedSymbol_.size();
    }
    /**
     * <pre>
     * Any symbols this file auto-generates/exports (eg. &#64;+id/foo in an XML file).
     * </pre>
     *
     * <code>repeated .CompiledFile.Symbol exported_symbol = 5;</code>
     */
    @java.lang.Override
    public android.aapt.pb.internal.ResourcesInternal.CompiledFile.Symbol getExportedSymbol(int index) {
      return exportedSymbol_.get(index);
    }
    /**
     * <pre>
     * Any symbols this file auto-generates/exports (eg. &#64;+id/foo in an XML file).
     * </pre>
     *
     * <code>repeated .CompiledFile.Symbol exported_symbol = 5;</code>
     */
    public android.aapt.pb.internal.ResourcesInternal.CompiledFile.SymbolOrBuilder getExportedSymbolOrBuilder(
        int index) {
      return exportedSymbol_.get(index);
    }
    private void ensureExportedSymbolIsMutable() {
      com.google.protobuf.Internal.ProtobufList<android.aapt.pb.internal.ResourcesInternal.CompiledFile.Symbol> tmp = exportedSymbol_;
      if (!tmp.isModifiable()) {
        exportedSymbol_ =
            com.google.protobuf.GeneratedMessageLite.mutableCopy(tmp);
       }
    }

    /**
     * <pre>
     * Any symbols this file auto-generates/exports (eg. &#64;+id/foo in an XML file).
     * </pre>
     *
     * <code>repeated .CompiledFile.Symbol exported_symbol = 5;</code>
     */
    private void setExportedSymbol(
        int index, android.aapt.pb.internal.ResourcesInternal.CompiledFile.Symbol value) {
      value.getClass();
  ensureExportedSymbolIsMutable();
      exportedSymbol_.set(index, value);
    }
    /**
     * <pre>
     * Any symbols this file auto-generates/exports (eg. &#64;+id/foo in an XML file).
     * </pre>
     *
     * <code>repeated .CompiledFile.Symbol exported_symbol = 5;</code>
     */
    private void addExportedSymbol(android.aapt.pb.internal.ResourcesInternal.CompiledFile.Symbol value) {
      value.getClass();
  ensureExportedSymbolIsMutable();
      exportedSymbol_.add(value);
    }
    /**
     * <pre>
     * Any symbols this file auto-generates/exports (eg. &#64;+id/foo in an XML file).
     * </pre>
     *
     * <code>repeated .CompiledFile.Symbol exported_symbol = 5;</code>
     */
    private void addExportedSymbol(
        int index, android.aapt.pb.internal.ResourcesInternal.CompiledFile.Symbol value) {
      value.getClass();
  ensureExportedSymbolIsMutable();
      exportedSymbol_.add(index, value);
    }
    /**
     * <pre>
     * Any symbols this file auto-generates/exports (eg. &#64;+id/foo in an XML file).
     * </pre>
     *
     * <code>repeated .CompiledFile.Symbol exported_symbol = 5;</code>
     */
    private void addAllExportedSymbol(
        java.lang.Iterable<? extends android.aapt.pb.internal.ResourcesInternal.CompiledFile.Symbol> values) {
      ensureExportedSymbolIsMutable();
      com.google.protobuf.AbstractMessageLite.addAll(
          values, exportedSymbol_);
    }
    /**
     * <pre>
     * Any symbols this file auto-generates/exports (eg. &#64;+id/foo in an XML file).
     * </pre>
     *
     * <code>repeated .CompiledFile.Symbol exported_symbol = 5;</code>
     */
    private void clearExportedSymbol() {
      exportedSymbol_ = emptyProtobufList();
    }
    /**
     * <pre>
     * Any symbols this file auto-generates/exports (eg. &#64;+id/foo in an XML file).
     * </pre>
     *
     * <code>repeated .CompiledFile.Symbol exported_symbol = 5;</code>
     */
    private void removeExportedSymbol(int index) {
      ensureExportedSymbolIsMutable();
      exportedSymbol_.remove(index);
    }

    public static android.aapt.pb.internal.ResourcesInternal.CompiledFile parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data);
    }
    public static android.aapt.pb.internal.ResourcesInternal.CompiledFile parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data, extensionRegistry);
    }
    public static android.aapt.pb.internal.ResourcesInternal.CompiledFile parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data);
    }
    public static android.aapt.pb.internal.ResourcesInternal.CompiledFile parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data, extensionRegistry);
    }
    public static android.aapt.pb.internal.ResourcesInternal.CompiledFile parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data);
    }
    public static android.aapt.pb.internal.ResourcesInternal.CompiledFile parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data, extensionRegistry);
    }
    public static android.aapt.pb.internal.ResourcesInternal.CompiledFile parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, input);
    }
    public static android.aapt.pb.internal.ResourcesInternal.CompiledFile parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, input, extensionRegistry);
    }

    public static android.aapt.pb.internal.ResourcesInternal.CompiledFile parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return parseDelimitedFrom(DEFAULT_INSTANCE, input);
    }

    public static android.aapt.pb.internal.ResourcesInternal.CompiledFile parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return parseDelimitedFrom(DEFAULT_INSTANCE, input, extensionRegistry);
    }
    public static android.aapt.pb.internal.ResourcesInternal.CompiledFile parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, input);
    }
    public static android.aapt.pb.internal.ResourcesInternal.CompiledFile parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, input, extensionRegistry);
    }

    public static Builder newBuilder() {
      return (Builder) DEFAULT_INSTANCE.createBuilder();
    }
    public static Builder newBuilder(android.aapt.pb.internal.ResourcesInternal.CompiledFile prototype) {
      return DEFAULT_INSTANCE.createBuilder(prototype);
    }

    /**
     * <pre>
     * The top level message representing an external resource file (layout XML, PNG, etc).
     * This is used to represent a compiled file before it is linked. Only useful to aapt2.
     * </pre>
     *
     * Protobuf type {@code CompiledFile}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageLite.Builder<
          android.aapt.pb.internal.ResourcesInternal.CompiledFile, Builder> implements
        // @@protoc_insertion_point(builder_implements:CompiledFile)
        android.aapt.pb.internal.ResourcesInternal.CompiledFileOrBuilder {
      // Construct using android.aapt.pb.internal.ResourcesInternal.CompiledFile.newBuilder()
      private Builder() {
        super(DEFAULT_INSTANCE);
      }


      /**
       * <pre>
       * The name of the resource (in the form package:type/name).
       * </pre>
       *
       * <code>string resource_name = 1;</code>
       * @return The resourceName.
       */
      @java.lang.Override
      public java.lang.String getResourceName() {
        return instance.getResourceName();
      }
      /**
       * <pre>
       * The name of the resource (in the form package:type/name).
       * </pre>
       *
       * <code>string resource_name = 1;</code>
       * @return The bytes for resourceName.
       */
      @java.lang.Override
      public com.google.protobuf.ByteString
          getResourceNameBytes() {
        return instance.getResourceNameBytes();
      }
      /**
       * <pre>
       * The name of the resource (in the form package:type/name).
       * </pre>
       *
       * <code>string resource_name = 1;</code>
       * @param value The resourceName to set.
       * @return This builder for chaining.
       */
      public Builder setResourceName(
          java.lang.String value) {
        copyOnWrite();
        instance.setResourceName(value);
        return this;
      }
      /**
       * <pre>
       * The name of the resource (in the form package:type/name).
       * </pre>
       *
       * <code>string resource_name = 1;</code>
       * @return This builder for chaining.
       */
      public Builder clearResourceName() {
        copyOnWrite();
        instance.clearResourceName();
        return this;
      }
      /**
       * <pre>
       * The name of the resource (in the form package:type/name).
       * </pre>
       *
       * <code>string resource_name = 1;</code>
       * @param value The bytes for resourceName to set.
       * @return This builder for chaining.
       */
      public Builder setResourceNameBytes(
          com.google.protobuf.ByteString value) {
        copyOnWrite();
        instance.setResourceNameBytes(value);
        return this;
      }

      /**
       * <pre>
       * The configuration for which the resource is defined.
       * </pre>
       *
       * <code>.Configuration config = 2;</code>
       */
      @java.lang.Override
      public boolean hasConfig() {
        return instance.hasConfig();
      }
      /**
       * <pre>
       * The configuration for which the resource is defined.
       * </pre>
       *
       * <code>.Configuration config = 2;</code>
       */
      @java.lang.Override
      public com.android.aapt.ConfigurationOuterClass.Configuration getConfig() {
        return instance.getConfig();
      }
      /**
       * <pre>
       * The configuration for which the resource is defined.
       * </pre>
       *
       * <code>.Configuration config = 2;</code>
       */
      public Builder setConfig(com.android.aapt.ConfigurationOuterClass.Configuration value) {
        copyOnWrite();
        instance.setConfig(value);
        return this;
        }
      /**
       * <pre>
       * The configuration for which the resource is defined.
       * </pre>
       *
       * <code>.Configuration config = 2;</code>
       */
      public Builder setConfig(
          com.android.aapt.ConfigurationOuterClass.Configuration.Builder builderForValue) {
        copyOnWrite();
        instance.setConfig(builderForValue.build());
        return this;
      }
      /**
       * <pre>
       * The configuration for which the resource is defined.
       * </pre>
       *
       * <code>.Configuration config = 2;</code>
       */
      public Builder mergeConfig(com.android.aapt.ConfigurationOuterClass.Configuration value) {
        copyOnWrite();
        instance.mergeConfig(value);
        return this;
      }
      /**
       * <pre>
       * The configuration for which the resource is defined.
       * </pre>
       *
       * <code>.Configuration config = 2;</code>
       */
      public Builder clearConfig() {  copyOnWrite();
        instance.clearConfig();
        return this;
      }

      /**
       * <pre>
       * The type of the file.
       * </pre>
       *
       * <code>.FileReference.Type type = 3;</code>
       * @return The enum numeric value on the wire for type.
       */
      @java.lang.Override
      public int getTypeValue() {
        return instance.getTypeValue();
      }
      /**
       * <pre>
       * The type of the file.
       * </pre>
       *
       * <code>.FileReference.Type type = 3;</code>
       * @param value The type to set.
       * @return This builder for chaining.
       */
      public Builder setTypeValue(int value) {
        copyOnWrite();
        instance.setTypeValue(value);
        return this;
      }
      /**
       * <pre>
       * The type of the file.
       * </pre>
       *
       * <code>.FileReference.Type type = 3;</code>
       * @return The type.
       */
      @java.lang.Override
      public com.android.aapt.Resources.FileReference.Type getType() {
        return instance.getType();
      }
      /**
       * <pre>
       * The type of the file.
       * </pre>
       *
       * <code>.FileReference.Type type = 3;</code>
       * @param value The enum numeric value on the wire for type to set.
       * @return This builder for chaining.
       */
      public Builder setType(com.android.aapt.Resources.FileReference.Type value) {
        copyOnWrite();
        instance.setType(value);
        return this;
      }
      /**
       * <pre>
       * The type of the file.
       * </pre>
       *
       * <code>.FileReference.Type type = 3;</code>
       * @return This builder for chaining.
       */
      public Builder clearType() {
        copyOnWrite();
        instance.clearType();
        return this;
      }

      /**
       * <pre>
       * The filesystem path to where the source file originated.
       * Mainly used to display helpful error messages.
       * </pre>
       *
       * <code>string source_path = 4;</code>
       * @return The sourcePath.
       */
      @java.lang.Override
      public java.lang.String getSourcePath() {
        return instance.getSourcePath();
      }
      /**
       * <pre>
       * The filesystem path to where the source file originated.
       * Mainly used to display helpful error messages.
       * </pre>
       *
       * <code>string source_path = 4;</code>
       * @return The bytes for sourcePath.
       */
      @java.lang.Override
      public com.google.protobuf.ByteString
          getSourcePathBytes() {
        return instance.getSourcePathBytes();
      }
      /**
       * <pre>
       * The filesystem path to where the source file originated.
       * Mainly used to display helpful error messages.
       * </pre>
       *
       * <code>string source_path = 4;</code>
       * @param value The sourcePath to set.
       * @return This builder for chaining.
       */
      public Builder setSourcePath(
          java.lang.String value) {
        copyOnWrite();
        instance.setSourcePath(value);
        return this;
      }
      /**
       * <pre>
       * The filesystem path to where the source file originated.
       * Mainly used to display helpful error messages.
       * </pre>
       *
       * <code>string source_path = 4;</code>
       * @return This builder for chaining.
       */
      public Builder clearSourcePath() {
        copyOnWrite();
        instance.clearSourcePath();
        return this;
      }
      /**
       * <pre>
       * The filesystem path to where the source file originated.
       * Mainly used to display helpful error messages.
       * </pre>
       *
       * <code>string source_path = 4;</code>
       * @param value The bytes for sourcePath to set.
       * @return This builder for chaining.
       */
      public Builder setSourcePathBytes(
          com.google.protobuf.ByteString value) {
        copyOnWrite();
        instance.setSourcePathBytes(value);
        return this;
      }

      /**
       * <pre>
       * Any symbols this file auto-generates/exports (eg. &#64;+id/foo in an XML file).
       * </pre>
       *
       * <code>repeated .CompiledFile.Symbol exported_symbol = 5;</code>
       */
      @java.lang.Override
      public java.util.List<android.aapt.pb.internal.ResourcesInternal.CompiledFile.Symbol> getExportedSymbolList() {
        return java.util.Collections.unmodifiableList(
            instance.getExportedSymbolList());
      }
      /**
       * <pre>
       * Any symbols this file auto-generates/exports (eg. &#64;+id/foo in an XML file).
       * </pre>
       *
       * <code>repeated .CompiledFile.Symbol exported_symbol = 5;</code>
       */
      @java.lang.Override
      public int getExportedSymbolCount() {
        return instance.getExportedSymbolCount();
      }/**
       * <pre>
       * Any symbols this file auto-generates/exports (eg. &#64;+id/foo in an XML file).
       * </pre>
       *
       * <code>repeated .CompiledFile.Symbol exported_symbol = 5;</code>
       */
      @java.lang.Override
      public android.aapt.pb.internal.ResourcesInternal.CompiledFile.Symbol getExportedSymbol(int index) {
        return instance.getExportedSymbol(index);
      }
      /**
       * <pre>
       * Any symbols this file auto-generates/exports (eg. &#64;+id/foo in an XML file).
       * </pre>
       *
       * <code>repeated .CompiledFile.Symbol exported_symbol = 5;</code>
       */
      public Builder setExportedSymbol(
          int index, android.aapt.pb.internal.ResourcesInternal.CompiledFile.Symbol value) {
        copyOnWrite();
        instance.setExportedSymbol(index, value);
        return this;
      }
      /**
       * <pre>
       * Any symbols this file auto-generates/exports (eg. &#64;+id/foo in an XML file).
       * </pre>
       *
       * <code>repeated .CompiledFile.Symbol exported_symbol = 5;</code>
       */
      public Builder setExportedSymbol(
          int index, android.aapt.pb.internal.ResourcesInternal.CompiledFile.Symbol.Builder builderForValue) {
        copyOnWrite();
        instance.setExportedSymbol(index,
            builderForValue.build());
        return this;
      }
      /**
       * <pre>
       * Any symbols this file auto-generates/exports (eg. &#64;+id/foo in an XML file).
       * </pre>
       *
       * <code>repeated .CompiledFile.Symbol exported_symbol = 5;</code>
       */
      public Builder addExportedSymbol(android.aapt.pb.internal.ResourcesInternal.CompiledFile.Symbol value) {
        copyOnWrite();
        instance.addExportedSymbol(value);
        return this;
      }
      /**
       * <pre>
       * Any symbols this file auto-generates/exports (eg. &#64;+id/foo in an XML file).
       * </pre>
       *
       * <code>repeated .CompiledFile.Symbol exported_symbol = 5;</code>
       */
      public Builder addExportedSymbol(
          int index, android.aapt.pb.internal.ResourcesInternal.CompiledFile.Symbol value) {
        copyOnWrite();
        instance.addExportedSymbol(index, value);
        return this;
      }
      /**
       * <pre>
       * Any symbols this file auto-generates/exports (eg. &#64;+id/foo in an XML file).
       * </pre>
       *
       * <code>repeated .CompiledFile.Symbol exported_symbol = 5;</code>
       */
      public Builder addExportedSymbol(
          android.aapt.pb.internal.ResourcesInternal.CompiledFile.Symbol.Builder builderForValue) {
        copyOnWrite();
        instance.addExportedSymbol(builderForValue.build());
        return this;
      }
      /**
       * <pre>
       * Any symbols this file auto-generates/exports (eg. &#64;+id/foo in an XML file).
       * </pre>
       *
       * <code>repeated .CompiledFile.Symbol exported_symbol = 5;</code>
       */
      public Builder addExportedSymbol(
          int index, android.aapt.pb.internal.ResourcesInternal.CompiledFile.Symbol.Builder builderForValue) {
        copyOnWrite();
        instance.addExportedSymbol(index,
            builderForValue.build());
        return this;
      }
      /**
       * <pre>
       * Any symbols this file auto-generates/exports (eg. &#64;+id/foo in an XML file).
       * </pre>
       *
       * <code>repeated .CompiledFile.Symbol exported_symbol = 5;</code>
       */
      public Builder addAllExportedSymbol(
          java.lang.Iterable<? extends android.aapt.pb.internal.ResourcesInternal.CompiledFile.Symbol> values) {
        copyOnWrite();
        instance.addAllExportedSymbol(values);
        return this;
      }
      /**
       * <pre>
       * Any symbols this file auto-generates/exports (eg. &#64;+id/foo in an XML file).
       * </pre>
       *
       * <code>repeated .CompiledFile.Symbol exported_symbol = 5;</code>
       */
      public Builder clearExportedSymbol() {
        copyOnWrite();
        instance.clearExportedSymbol();
        return this;
      }
      /**
       * <pre>
       * Any symbols this file auto-generates/exports (eg. &#64;+id/foo in an XML file).
       * </pre>
       *
       * <code>repeated .CompiledFile.Symbol exported_symbol = 5;</code>
       */
      public Builder removeExportedSymbol(int index) {
        copyOnWrite();
        instance.removeExportedSymbol(index);
        return this;
      }

      // @@protoc_insertion_point(builder_scope:CompiledFile)
    }
    @java.lang.Override
    @java.lang.SuppressWarnings({"unchecked", "fallthrough"})
    protected final java.lang.Object dynamicMethod(
        com.google.protobuf.GeneratedMessageLite.MethodToInvoke method,
        java.lang.Object arg0, java.lang.Object arg1) {
      switch (method) {
        case NEW_MUTABLE_INSTANCE: {
          return new android.aapt.pb.internal.ResourcesInternal.CompiledFile();
        }
        case NEW_BUILDER: {
          return new Builder();
        }
        case BUILD_MESSAGE_INFO: {
            java.lang.Object[] objects = new java.lang.Object[] {
              "bitField0_",
              "resourceName_",
              "config_",
              "type_",
              "sourcePath_",
              "exportedSymbol_",
              android.aapt.pb.internal.ResourcesInternal.CompiledFile.Symbol.class,
            };
            java.lang.String info =
                "\u0000\u0005\u0000\u0001\u0001\u0005\u0005\u0000\u0001\u0000\u0001\u0208\u0002\u1009" +
                "\u0000\u0003\f\u0004\u0208\u0005\u001b";
            return newMessageInfo(DEFAULT_INSTANCE, info, objects);
        }
        // fall through
        case GET_DEFAULT_INSTANCE: {
          return DEFAULT_INSTANCE;
        }
        case GET_PARSER: {
          com.google.protobuf.Parser<android.aapt.pb.internal.ResourcesInternal.CompiledFile> parser = PARSER;
          if (parser == null) {
            synchronized (android.aapt.pb.internal.ResourcesInternal.CompiledFile.class) {
              parser = PARSER;
              if (parser == null) {
                parser =
                    new DefaultInstanceBasedParser<android.aapt.pb.internal.ResourcesInternal.CompiledFile>(
                        DEFAULT_INSTANCE);
                PARSER = parser;
              }
            }
          }
          return parser;
      }
      case GET_MEMOIZED_IS_INITIALIZED: {
        return (byte) 1;
      }
      case SET_MEMOIZED_IS_INITIALIZED: {
        return null;
      }
      }
      throw new UnsupportedOperationException();
    }


    // @@protoc_insertion_point(class_scope:CompiledFile)
    private static final android.aapt.pb.internal.ResourcesInternal.CompiledFile DEFAULT_INSTANCE;
    static {
      CompiledFile defaultInstance = new CompiledFile();
      // New instances are implicitly immutable so no need to make
      // immutable.
      DEFAULT_INSTANCE = defaultInstance;
      com.google.protobuf.GeneratedMessageLite.registerDefaultInstance(
        CompiledFile.class, defaultInstance);
    }

    public static android.aapt.pb.internal.ResourcesInternal.CompiledFile getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static volatile com.google.protobuf.Parser<CompiledFile> PARSER;

    public static com.google.protobuf.Parser<CompiledFile> parser() {
      return DEFAULT_INSTANCE.getParserForType();
    }
  }


  static {
  }

  // @@protoc_insertion_point(outer_class_scope)
}
